@baseUrl = http://localhost:3000

### Read all films
GET {{baseUrl}}/films

### Read a single film
GET {{baseUrl}}/films/2
### Read a single film that does not exist
GET {{baseUrl}}/films/999
 
### duractionFilter

GET {{baseUrl}}/films?minimum-duration=100
 
### Create a new film
POST {{baseUrl}}/films
Content-Type: application/json

{
  "title": "New Film",
  "director": "John Doe",
  "duration": 120,
  "budget": 100,
  "description": "A new film description.",
  "imageUrl": "https://image.tmdb.org/t/p/newfilm.jpg"
}
